# Generated by Django 5.1.4 on 2024-12-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('venue', models.CharField(max_length=255)),
                ('timing', models.DateTimeField()),
                ('name_of_coordinator', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('upload_poster', models.ImageField(blank=True, null=True, upload_to='event_posters/')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('usn', models.CharField(max_length=20, unique=True)),
                ('branch', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
    ]
